// Static HTML rendering for the reusable technology/legal-template catalogue and dossier pages.
// The builder supplies already-shaped records; this module performs no I/O and reads no clock.

import fmt from './fmt.js';
import siteNav from './site-nav.js';
import {
    breadcrumbLd, contactStylesheet, insertContact, ldGraph, organizationLd, reportLd, seoHeadTags, webPageLd
} from './site-seo.mjs';

const { escapeHtml, isSafeUrl, humanizeSlug, cardSlug, fmtDate } = fmt;
const DASH = '—';

function esc(value) {
    return escapeHtml(value === null || value === undefined || value === '' ? DASH : String(value));
}

function yn(value) {
    return value === true ? 'yes' : value === false ? 'no' : DASH;
}

function link(url, label = 'source ↗') {
    return isSafeUrl(url) ? `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)}</a>` : '';
}

function paragraph(value, empty = 'Not established.') {
    return `<p>${escapeHtml(typeof value === 'string' && value.trim() ? value.trim() : empty)}</p>`;
}

function layoutHead({ title, description, socialDescription = null, canonical = null, version = '', image = null, jsonLd = null, type = 'article' }) {
    const v = version ? `?v=${encodeURIComponent(version)}` : '';
    const sep = '\n    ';
    return `<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    ${siteNav.themeScriptHtml('../')}
    ${seoHeadTags({ title, description, socialDescription, url: canonical, type, image, jsonLd, sep })}
    <link rel="icon" type="image/svg+xml" href="../images/variant3.svg" />
    <link rel="stylesheet" href="../app-shell.css${v}" />
    <link rel="stylesheet" href="../templates.css${v}" />
    ${contactStylesheet('../')}`;
}

function pageShell({ body, ...head }) {
    return insertContact(`<!doctype html>
<!-- Generated by stocks/build-legal-templates.mjs. Do not edit: rebuilt from reviewed issuer dossiers. -->
<html lang="en">
<head>
    ${layoutHead(head)}
</head>
<body>
${body}
</body>
</html>
`, '../');
}

function confidenceGrid(template) {
    return `<div class="confidence-grid">${template.evidenceConfidence.map((facet) =>
        `<article class="confidence confidence-${escapeHtml(facet.level)}">` +
        `<span>${escapeHtml(facet.label)}</span><strong>${escapeHtml(facet.levelLabel)}</strong>` +
        `<small>${facet.claimCount} sourced claim${facet.claimCount === 1 ? '' : 's'}` +
        `${facet.externalChangeCount ? ` · ${facet.externalChangeCount} external change${facet.externalChangeCount === 1 ? '' : 's'}` : ''}` +
        `${facet.latestCheckedAt ? ` · checked ${escapeHtml(fmtDate(facet.latestCheckedAt))}` : ''}</small></article>`
    ).join('')}</div>`;
}

function traceabilityHtml(template) {
    const kindLabels = {
        fact: 'Observed fact',
        'issuer-assertion': 'Issuer / document assertion',
        interpretation: 'Analytical interpretation',
        unresolved: 'Unresolved question'
    };
    return `<div class="conclusion-ledger">${(template.conclusions ?? []).map((conclusion) => {
        const evidence = (conclusion.evidence ?? []).slice(0, 4).map((row) => `<li>` +
            `<div class="citation-head"><span class="claim-kind claim-kind-${escapeHtml(row.kind)}">${esc(kindLabels[row.kind] ?? row.kind)}</span>` +
            `<strong>${esc(row.field)}</strong></div>` +
            `${row.quote ? `<blockquote>${esc(row.quote)}</blockquote>` : '<p class="unknown">No exact quotation recorded.</p>'}` +
            `<p class="citation-meta">${row.sourceUrl ? link(row.sourceUrl, row.sourceTitle ?? 'source ↗') : esc(row.sourceTitle)}` +
            `${row.locator ? ` · ${esc(row.locator)}` : ''}` +
            ` · ${esc(row.sourceAuthorityLabel)}${row.precedenceRank ? ` · precedence ${row.precedenceRank}` : ''}` +
            `${row.checkedAt ? ` · checked ${esc(fmtDate(row.checkedAt))}` : ''}</p></li>`).join('');
        const extra = Math.max(0, (conclusion.evidence ?? []).length - 4);
        return `<article class="conclusion-card${conclusion.underReview?.length ? ' conclusion-under-review' : ''}" id="conclusion-${escapeHtml(conclusion.id)}">` +
            `<header><span class="claim-kind claim-kind-${escapeHtml(conclusion.kind)}">${esc(kindLabels[conclusion.kind] ?? conclusion.kind)}</span>` +
            `<h3>${esc(conclusion.label)}</h3></header>` +
            `${conclusion.underReview?.length ? `<p class="under-review"><strong>Under review:</strong> ${esc(conclusion.underReview.map((item) => item.title).join('; '))}</p>` : ''}` +
            `${paragraph(conclusion.conclusion, 'This conclusion is not established.')}` +
            `<dl class="trace-scope"><dt>Governing law</dt><dd>${esc(conclusion.governingLaw)}</dd>` +
            `<dt>Holder scope</dt><dd>${conclusion.eligibleHolders?.length ? esc(conclusion.eligibleHolders.join('; ')) : 'Not established'}</dd>` +
            `<dt>Reviewed</dt><dd>${esc(fmtDate(conclusion.reviewedAt))}</dd></dl>` +
            `<details><summary>Evidence and exact clauses (${(conclusion.evidence ?? []).length})</summary>` +
            `<ol class="citation-list">${evidence || '<li>No supporting claim is recorded; this remains unresolved.</li>'}</ol>` +
            `${extra ? `<p class="muted">${extra} additional supporting claim${extra === 1 ? '' : 's'} remain in the source register.</p>` : ''}</details></article>`;
    }).join('')}</div>`;
}

function chainHtml(template) {
    const chain = template.claimChain ?? {};
    const nodes = chain.ownershipPath ?? [];
    const cards = nodes.map((node) => {
        const parties = (node.parties ?? []).length
            ? `<ul>${node.parties.map((party) => `<li><strong>${esc(party.name)}</strong>` +
                `${party.jurisdiction ? `<span>${esc(party.jurisdiction)}</span>` : ''}</li>`).join('')}</ul>`
            : '<p class="unknown">No named party established.</p>';
        return `<article class="chain-node" data-actor="${esc(node.actor)}"><span>${esc(node.label)}</span>${parties}</article>` +
            (node.relationshipToNext ? `<div class="chain-connector"><span>${esc(node.relationshipToNext)}</span><b aria-hidden="true">→</b></div>` : '');
    }).join('');
    const dependencies = (chain.dependencies ?? []).map((node) => `<article><span>${esc(node.label)}</span>` +
        `${(node.parties ?? []).length ? `<strong>${esc(node.parties.map((party) => party.name).join('; '))}</strong>` : '<strong>Unnamed dependency</strong>'}` +
        `<small>${node.affects?.length ? `Affects ${esc(node.affects.join(', '))}` : 'Role is recorded; affected right is not yet mapped.'}</small></article>`).join('');
    const links = (chain.links ?? []).map((flow) => `<li><strong>${esc(flow.label)}</strong>` +
        `<span>${esc(flow.evidence)} · ${esc(flow.verification)}</span><p>${esc(flow.summary)}</p></li>`).join('');
    return `<div class="chain-direction"><span>Underlying legal/economic right</span><span>Token holder</span></div>` +
        `<div class="claim-chain" aria-label="Ownership chain from the underlying company to the token holder">${cards || '<p>No ownership path is recorded.</p>'}</div>` +
        `<h3>Parties that can interrupt or enforce the chain</h3><div class="chain-dependencies">${dependencies || '<p>No additional named dependency is recorded.</p>'}</div>` +
        `<details><summary>Rights flowing through the chain (${(chain.links ?? []).length})</summary>` +
        `<ul class="flow-list">${links || '<li>No rights-flow analysis recorded.</li>'}</ul></details>`;
}

function assetsHtml(template, cardSlugs) {
    const items = template.inheritance.items ?? [];
    const visible = items.slice(0, 40);
    const chips = visible.map((asset) => {
        const slug = cardSlugs?.get(asset.mint) ?? cardSlug(asset.symbol, asset.mint);
        return `<li><a href="../cards/${encodeURIComponent(slug)}.html"><strong>${esc(asset.symbol ?? asset.name)}</strong>` +
            `<span>${esc(asset.underlyingTicker ?? asset.instrumentType)}</span></a></li>`;
    }).join('');
    const remaining = items.length - visible.length;
    return `<p><strong>${items.length}</strong> current token address${items.length === 1 ? '' : 'es'} across ` +
        `<strong>${template.inheritance.underlyingCount}</strong> underlying${template.inheritance.underlyingCount === 1 ? '' : 's'} ` +
        `${items.length === 1 ? 'inherits' : 'inherit'} this analysis.</p>` +
        `<ul class="asset-chips">${chips}</ul>` +
        (remaining > 0 ? `<p class="muted">${remaining} more inherit the same template; use the app’s issuer filter for the complete mint list.</p>` : '') +
        `<p class="exception-note"><strong>Exceptions:</strong> ${template.inheritance.exceptions.length
            ? `${template.inheritance.exceptions.length} asset-specific exception(s) are recorded.`
            : 'none recorded. An asset-specific conclusion must be shown here before it overrides the inherited template.'}</p>`;
}

function sourceHtml(template) {
    const changes = template.sourceAuthority.changes ?? [];
    const rows = (template.sourceAuthority.sources ?? []).slice(0, 30).map((source) => `<tr>` +
        `<td><strong>${esc(source.authorityLabel)}</strong><small>${esc(source.type)}</small></td>` +
        `<td>${source.url ? link(source.url, source.title) : esc(source.title)}` +
        `${source.archiveUrl ? ` <span class="archive">${link(source.archiveUrl, 'archive ↗')}</span>` : ''}</td>` +
        `<td>${esc(source.version ?? 'not structured')}</td>` +
        `<td>${esc(source.effectiveDate ?? 'not structured')}</td>` +
        `<td>${esc(source.accessedAt ? fmtDate(source.accessedAt) : null)}</td>` +
        `<td>${source.claimCount}</td></tr>`).join('');
    const precedence = template.sourceAuthority.precedence.map((level) => `<li>` +
        `<span>${level.rank}</span><div><strong>${esc(level.label)}</strong><p>${esc(level.rule)}</p></div></li>`).join('');
    const changeRows = changes.length ? `<ul class="conflict-list">${changes.map((claim) => `<li>` +
        `<strong>${esc(claim.field)} · ${esc(claim.status)}</strong>${paragraph(claim.note, 'The external source change is recorded in the underlying claim.')}` +
        `${link(claim.url)}</li>`).join('')}</ul>` : '<p>No unresolved external source change is currently recorded for this template.</p>';
    return `<p class="method-rule">${esc(template.sourceAuthority.rule)}</p>` +
        `<ol class="precedence">${precedence}</ol>` +
        `<h3>Recorded external source changes</h3>${changeRows}` +
        `<h3>Document register</h3><p class="muted">“Not structured” marks an evidence gap. We do not copy a date from a document title into its metadata.</p>` +
        `<div class="table-wrap"><table><thead><tr><th>Authority</th><th>Document</th><th>Version</th><th>Effective</th><th>Checked</th><th>Claims</th></tr></thead>` +
        `<tbody>${rows}</tbody></table></div>`;
}

function scopeHtml(template) {
    const scope = template.scope;
    const audience = scope.eligibleHolders.length ? `<ul>${scope.eligibleHolders.map((holder) => `<li>` +
        `<strong>${esc(holder.name)}</strong>${holder.jurisdiction ? ` · ${esc(holder.jurisdiction)}` : ''}` +
        `${holder.note ? `<p>${esc(holder.note)}</p>` : ''}${link(holder.source)}</li>`).join('')}</ul>` : '<p>No holder class is named.</p>';
    return `<div class="two-col"><article><h3>Governing scope</h3><dl class="facts">` +
        `<dt>Entity jurisdictions</dt><dd>${esc(scope.entityJurisdiction)}</dd>` +
        `<dt>Governing law</dt><dd>${esc(scope.governingLaw)}</dd>` +
        `<dt>Allowlist</dt><dd>${yn(scope.transfer.allowlist)}</dd>` +
        `<dt>KYC to hold</dt><dd>${yn(scope.transfer.kycToHold)}</dd>` +
        `<dt>US persons excluded</dt><dd>${yn(scope.transfer.usPersonsExcluded)}</dd>` +
        `<dt>On-chain mechanism</dt><dd>${esc(scope.transfer.mechanism)}</dd></dl></article>` +
        `<article><h3>Eligible holder classes</h3>${audience}</article></div>` +
        `<p class="callout">${esc(scope.distinction)}</p>`;
}

function insolvencyHtml(template) {
    const value = template.insolvency;
    return `<div class="verdict verdict-${escapeHtml(value.rating)}"><strong>${esc(humanizeSlug(value.rating))}</strong>${paragraph(value.headline)}</div>` +
        `<dl class="facts"><dt>Bankruptcy remote</dt><dd>${yn(value.bankruptcyRemote)}</dd>` +
        `<dt>Security interest</dt><dd>${yn(value.securityInterest.exists)}</dd>` +
        `<dt>Security holder</dt><dd>${esc(value.securityInterest.holder)}</dd>` +
        `<dt>Recorded priority</dt><dd>${esc(value.securityInterest.priority)}</dd>` +
        `<dt>Collateral ratio</dt><dd>${esc(value.collateral.ratio)}</dd>` +
        `<dt>Collateral composition</dt><dd>${esc(value.collateral.composition)}</dd>` +
        `<dt>Rehypothecation</dt><dd>${esc(value.collateral.rehypothecation)}</dd>` +
        `<dt>On-loan amount disclosed</dt><dd>${yn(value.collateral.onLoanDisclosed)}</dd>` +
        `<dt>Segregation / trust evidence</dt><dd>${esc(value.operationalDetails.segregationOrTrust)}</dd>` +
        `<dt>Omnibus / commingling evidence</dt><dd>${esc(value.operationalDetails.omnibusOrCommingling)}</dd>` +
        `<dt>Perfection / priority evidence</dt><dd>${esc(value.operationalDetails.perfectionOrPriority)}</dd>` +
        `<dt>Custodian lien / set-off evidence</dt><dd>${esc(value.operationalDetails.custodianLienOrSetoff)}</dd>` +
        `<dt>Who can enforce</dt><dd>${esc(value.operationalDetails.enforcementStanding)}</dd></dl>` +
        `<h3>Holder standing</h3>${paragraph(value.holderStanding)}` +
        `<p class="callout">${esc(value.caveat)}</p>`;
}

function corporateHtml(template) {
    const value = template.corporateActions;
    return `<p class="mode-chip">${esc(humanizeSlug(value.mode))}</p><dl class="facts">` +
        `<dt>Dividends</dt><dd>${esc(value.dividends)}</dd>` +
        `<dt>Voting</dt><dd>${esc(value.voting)}</dd>` +
        `<dt>Other corporate actions</dt><dd>${esc(value.actions)}</dd></dl>` +
        `<p class="callout">${esc(value.caveat)}</p>`;
}

function controlHtml(template) {
    const value = template.control ?? {};
    const rows = (Array.isArray(value.authorities) ? value.authorities : []).map((row) => {
        const governance = row.governance ?? {};
        const controller = [governance.controller, governance.signerThreshold,
            governance.upgradeAuthority ? `upgrade authority: ${governance.upgradeAuthority}` : null]
            .filter(Boolean).join(' · ');
        return `<tr><td><strong>${esc(row.label)}</strong></td>`
            + `<td>${esc(humanizeSlug(row.technicalCapability))}</td>`
            + `<td>${esc(humanizeSlug(governance.type))}</td>`
            + `<td>${esc(controller, 'Not established')}</td>`
            + `<td>${esc(governance.observedAt ? fmtDate(governance.observedAt) : null)}</td></tr>`;
    }).join('');
    return `<div class="verdict verdict-${escapeHtml(value.status ?? 'unknown')}"><strong>${esc(humanizeSlug(value.status))}</strong>`
        + `${paragraph(value.headline)}</div><p class="muted">A programme or PDA label is not the ultimate controller. Thresholds apply only to the role shown; differently privileged members are not treated as equivalent voters.</p>`
        + `<div class="table-wrap"><table><thead><tr><th>Capability</th><th>Installed</th><th>Effective governance</th><th>Controller / threshold</th><th>Observed</th></tr></thead>`
        + `<tbody>${rows || '<tr><td colspan="5">No installed authority path was established.</td></tr>'}</tbody></table></div>`;
}

function redemptionHtml(template) {
    const value = template.redemption;
    const answerHtml = (answer) => {
        const summary = answer?.value === true ? 'Yes' : answer?.value === false ? 'No'
            : answer?.value === null || answer?.value === undefined ? 'Not established'
                : String(answer.summary ?? answer.value);
        const scope = answer?.scopeContext ?? {};
        const notes = [scope.source ? `Source scope: ${scope.source}` : null,
            scope.holders ? `Holder scope: ${scope.holders}` : null,
            scope.jurisdictions ? `Jurisdiction scope: ${scope.jurisdictions}` : null].filter(Boolean);
        const detail = typeof answer?.completeText === 'string' && answer.completeText
            ? `<details class="redemption-term"><summary>${esc(summary)}</summary><p>${esc(answer.completeText)}</p>`
                + `${notes.length ? `<small>${esc(notes.join(' · '))}</small>` : ''}</details>`
            : `<strong>${esc(summary)}</strong>`;
        return `<dt>${esc(answer?.label, 'Redemption term')}</dt><dd>${detail}<small class="evidence-state">${esc(humanizeSlug(answer?.evidence ?? 'unknown'))}</small></dd>`;
    };
    const answers = value.usability?.fields ?? [];
    return `<div class="redemption-proof"><strong>${esc(humanizeSlug(value.evidenceStatus))}</strong>${paragraph(value.evidenceLabel)}</div>` +
        `<p class="muted">Programme-level answer. Product examples stay labelled and do not become terms for another token.</p>` +
        `<dl class="facts">${answers.slice(0, 8).map(answerHtml).join('')}` +
        `<dt>Timing / SLA</dt><dd>${esc(value.timing)}</dd>` +
        `<dt>Secondary-market exit</dt><dd>Asset-specific · inspect the exact-token report for current venues and liquidity.</dd>` +
        `<dt>Notes</dt><dd>${esc(value.notes)}</dd></dl>`;
}

/**
 * `ogImage` is `{url, alt, width, height}` (absolute) from the family image step, null for the site
 * image. `cardSlugs` is build-cards' collision-aware mint -> file-name map.
 */
export function renderTemplatePage(template, { baseUrl = null, version = '', cardSlugs = null, ogImage = null } = {}) {
    const origin = typeof baseUrl === 'string' && baseUrl.trim() ? baseUrl.trim().replace(/\/+$/, '') : null;
    const canonical = origin ? `${origin}/templates/${encodeURIComponent(template.id)}.html` : null;
    const body = siteNav.siteHeaderHtml('../', 'templates/') +
        `<main><p class="eyebrow">Technology + legal template</p><h1>${esc(template.legalTemplate)}</h1>` +
        `<p class="lede">${esc(template.summary)}</p>` +
        `${template.underReview?.length ? `<div class="under-review-banner"><strong>Legal conclusions under review</strong><span>${template.underReview.length} priority-zero evidence change${template.underReview.length === 1 ? '' : 's'} may affect this template. Treat the marked conclusions as provisional.</span><a href="../review.html?priority=P0&issuer=${encodeURIComponent(template.issuer.slug)}">Open review queue →</a></div>` : ''}` +
        `<div class="hero-facts"><span>${esc(template.issuer.name)}</span><span>${esc(template.technologyRecipe)}</span>` +
        `<span class="status status-${escapeHtml(template.composabilityStatus)}">DeFi ${esc(template.composabilityStatus)}</span>` +
        `<span>Reviewed ${esc(fmtDate(template.reviewedAt))}</span></div>` +
        `<section><h2>What this analysis covers</h2>${assetsHtml(template, cardSlugs)}</section>` +
        `<section><h2>Traceable conclusions</h2><p>Each conclusion carries its classification, exact supporting words, source authority, location, governing law, holder scope and review date. A statement in a document is weaker evidence than an independently observed outcome.</p>${traceabilityHtml(template)}</section>` +
        `<section><h2>Evidence confidence</h2><p>Confidence is stated per conclusion type, with no overall score.</p>${confidenceGrid(template)}</section>` +
        `<section><h2>Complete claim chain</h2><p>Possessing the token is only the first link. Each intermediary can add a separate contract, governing law and failure dependency.</p>${chainHtml(template)}</section>` +
        `<section><h2>Technical control</h2>${controlHtml(template)}</section>` +
        `<section><h2>Jurisdiction and holder eligibility</h2>${scopeHtml(template)}</section>` +
        `<section><h2>Insolvency and enforcement</h2>${insolvencyHtml(template)}</section>` +
        `<section><h2>Corporate actions</h2>${corporateHtml(template)}</section>` +
        `<section><h2>Redemption path</h2>${redemptionHtml(template)}</section>` +
        `<section><h2>Source authority and precedence</h2>${sourceHtml(template)}</section>` +
        `<section><h2>Open questions</h2>${template.openQuestions.length
            ? `<ul>${template.openQuestions.map((question) => `<li>${esc(question)}</li>`).join('')}</ul>`
            : '<p>No open question is currently recorded.</p>'}</section>` +
        `<footer><p>This is a template-level conclusion. A named asset inherits it unless an explicit exception is recorded above.</p>` +
        `<nav><a href="./index.html">All legal templates</a><a href="../stocks.html">Compare tokenized stocks</a></nav></footer></main>`;
    const title = `${template.issuer.name} legal template: ${template.technologyRecipe} — RWA Sonar`;
    const description = `${template.issuer.name}, ${template.technologyRecipe}: ${template.legalTemplate}. Claim chain, insolvency, eligibility, redemption and evidence.`;
    return pageShell({
        title,
        description,
        socialDescription: `${template.legalTemplate}: claim chain, insolvency, eligibility, redemption, corporate actions and evidence authority, inherited by ${template.inheritance.count} exact Solana token${template.inheritance.count === 1 ? '' : 's'}.`,
        canonical,
        image: ogImage,
        jsonLd: origin === null ? null : ldGraph([
            organizationLd(origin),
            reportLd({ origin, url: canonical, headline: `${template.issuer.name} legal template: ${template.legalTemplate}`, description,
                dateModified: template.reviewedAt ?? null, image: ogImage?.url ?? null,
                about: { '@type': 'Organization', name: template.issuer.name } }),
            breadcrumbLd([{ name: 'RWA Sonar', url: `${origin}/` }, { name: 'Legal templates', url: `${origin}/templates/` },
                { name: `${template.issuer.name}: ${template.technologyRecipe}`, url: canonical }])
        ]),
        body,
        version
    });
}

export function renderTemplateIndex(templates, { baseUrl = null, version = '', ogImage = null } = {}) {
    const origin = typeof baseUrl === 'string' && baseUrl.trim() ? baseUrl.trim().replace(/\/+$/, '') : null;
    const cards = templates.map((template) => `<article class="template-card"><p class="eyebrow">${esc(template.issuer.name)}</p>` +
        `<h2><a href="./${encodeURIComponent(template.id)}.html">${esc(template.legalTemplate)}</a></h2>` +
        `<p>${esc(template.summary)}</p><dl><dt>Technology</dt><dd>${esc(template.technologyRecipe)}</dd>` +
        `<dt>Inherited assets</dt><dd>${template.inheritance.count} token address${template.inheritance.count === 1 ? '' : 'es'} · ` +
        `${template.inheritance.underlyingCount} underlying${template.inheritance.underlyingCount === 1 ? '' : 's'}</dd>` +
        `<dt>Evidence</dt><dd>${template.evidenceConfidence.filter((row) => row.level !== 'unknown').length}/${template.evidenceConfidence.length} dimensions established</dd></dl>` +
        `<a class="open-template" href="./${encodeURIComponent(template.id)}.html">Open full legal analysis →</a></article>`).join('');
    const body = siteNav.siteHeaderHtml('../', 'templates/') +
        `<main><p class="eyebrow">Reusable legal architecture</p><h1>Technology + legal templates</h1>` +
        `<p class="lede">Assets inherit analysis only when both their issuer programme and observed on-chain control recipe match. One reviewed conclusion can then cover many tokens, and a token with a different recipe gets its own template.</p>` +
        `<div class="template-grid">${cards}</div>` +
        `<footer><a href="../stocks.html">Open the tokenized-stock app</a></footer></main>`;
    const canonical = origin ? `${origin}/templates/` : null;
    const description = 'Compare the legal and technical structures inherited by tokenized stocks on Solana: one reviewed template per issuer programme and control recipe.';
    return pageShell({
        title: 'Tokenized-stock legal templates — RWA Sonar',
        description,
        canonical,
        type: 'website',
        image: ogImage,
        jsonLd: origin === null ? null : ldGraph([
            organizationLd(origin),
            webPageLd({ origin, url: canonical, name: 'Tokenized-stock legal templates — RWA Sonar', description, type: 'CollectionPage' }),
            breadcrumbLd([{ name: 'RWA Sonar', url: `${origin}/` }, { name: 'Legal templates', url: canonical }])
        ]),
        body,
        version
    });
}
