-- Evidence and watch tables in schema `sonar` (stocks/EVIDENCE.md §1 and §3): the registry of
-- every URL the dossiers rely on (`source`), one row per fetch that produced new content
-- (`source_version`) and the detected changes (`change_event`). Written by
-- stocks/extract-sources.mjs and stocks/watch-sources.mjs. `claim` (EVIDENCE.md §1, slice 2) is
-- deliberately NOT created here.
-- Idempotent: re-running this file is a no-op.

-- `IF NOT EXISTS` emits a NOTICE per already-present object, which on a re-run is a screenful of
-- noise in the refresh log and nothing else. Quiet only NOTICE; warnings and errors still speak.
SET client_min_messages = warning;

-- Every object must end up owned by `geo_user`. The connecting role (zagreb_user / magician) is
-- a member, so switch to it; if we already ARE geo_user, or are a superuser that is not a member,
-- the guard leaves the session alone rather than failing the whole run.
DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

-- ---------------------------------------------------------------------------------------------
-- Sources. One row per URL we rely on. `id` is the first 12 hex characters of sha256(url), which
-- is also the on-disk directory name under stocks/data/sources/ — deterministic, so a loader
-- never has to look an id up and a re-run addresses exactly the same rows.
--
-- `status` extends EVIDENCE.md §1 (ok, changed, gone, blocked) with two states the watcher needs:
-- `new` for a source that has never been fetched, and `error` for a fetch that failed for a
-- reason that is neither "the document is gone" nor "the host refuses us" (5xx, timeout, reset).
-- A run with any `error` source must not report success, so the state has to be distinguishable.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.source (
    id              text PRIMARY KEY,
    url             text NOT NULL,
    kind            text NOT NULL,
    title           text,
    issuer_slug     text,
    found_in        jsonb,
    first_seen_at   timestamptz,
    last_checked_at timestamptz,
    last_changed_at timestamptz,
    check_every     interval NOT NULL DEFAULT '1 day',
    archive_url     text,
    status          text NOT NULL DEFAULT 'new',
    content_hash    text,
    http_status     int,
    error           text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT source_url_key    UNIQUE (url),
    CONSTRAINT source_kind_check CHECK (kind IN ('pdf', 'html', 'api', 'onchain')),
    CONSTRAINT source_status_check
        CHECK (status IN ('new', 'ok', 'changed', 'gone', 'blocked', 'error'))
);

CREATE INDEX IF NOT EXISTS source_issuer_slug_idx ON sonar.source (issuer_slug);
CREATE INDEX IF NOT EXISTS source_status_idx      ON sonar.source (status);
CREATE INDEX IF NOT EXISTS source_kind_idx        ON sonar.source (kind);

COMMENT ON COLUMN sonar.source.id IS 'left(sha256(url), 12) — also the stocks/data/sources/<id>/ directory';
COMMENT ON COLUMN sonar.source.found_in IS 'dossier field paths the URL was cited in, e.g. ["prestocks:documents[0].url"]';

-- ---------------------------------------------------------------------------------------------
-- Versions. One row per fetch that produced NEW content: an unchanged fetch only moves
-- source.last_checked_at, exactly as EVIDENCE.md §2.1 requires. `fetched_at` is when WE fetched;
-- `last_modified` and `etag` are only ever the server's own header values, never invented.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.source_version (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     text NOT NULL REFERENCES sonar.source(id) ON DELETE CASCADE,
    fetched_at    timestamptz NOT NULL,
    content_hash  text NOT NULL,
    bytes         bigint,
    text_chars    int,
    text_path     text,
    raw_path      text,
    archive_url   text,
    etag          text,
    last_modified text,
    diff_summary  text,
    diff_severity text,
    diff_method   text,
    diff_added    int,
    diff_removed  int,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT source_version_fetch_key UNIQUE (source_id, fetched_at),
    CONSTRAINT source_version_method_check
        CHECK (diff_method IS NULL OR diff_method IN ('none', 'quote-lost', 'keyword', 'llm')),
    CONSTRAINT source_version_severity_check
        CHECK (diff_severity IS NULL OR diff_severity IN ('info', 'caution', 'warning', 'critical'))
);

CREATE INDEX IF NOT EXISTS source_version_source_idx ON sonar.source_version (source_id, fetched_at DESC);

-- ---------------------------------------------------------------------------------------------
-- Change events (EVIDENCE.md §1, kinds per §3). One row per detected change, whatever watcher
-- found it: a document diff, a rotated authority key, a venue delisting. `evidence` carries the
-- source_version ids / tx signatures / snapshot dates the event was read from, so the feed can
-- always show what it was inferred from.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.change_event (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at     timestamptz NOT NULL,
    kind            text NOT NULL,
    subject_type    text NOT NULL,
    subject_id      text NOT NULL,
    field           text,
    before          text,
    after           text,
    severity        text NOT NULL,
    evidence        jsonb,
    summary         text,
    acknowledged_at timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT change_event_kind_check CHECK (kind IN (
        'legal-term', 'document-gone', 'authority-key', 'extension-toggle', 'rebase', 'supply',
        'treasury', 'holder-concentration', 'venue', 'float', 'liquidity', 'metadata', 'status')),
    CONSTRAINT change_event_severity_check
        CHECK (severity IN ('info', 'caution', 'warning', 'critical')),
    CONSTRAINT change_event_subject_type_check
        CHECK (subject_type IN ('issuer', 'token', 'source'))
);

CREATE INDEX IF NOT EXISTS change_event_detected_at_idx ON sonar.change_event (detected_at DESC);
CREATE INDEX IF NOT EXISTS change_event_severity_idx    ON sonar.change_event (severity);
CREATE INDEX IF NOT EXISTS change_event_kind_idx        ON sonar.change_event (kind);
CREATE INDEX IF NOT EXISTS change_event_subject_idx     ON sonar.change_event (subject_type, subject_id);

-- The same run must not be able to write the same event twice. `field` is nullable (a status
-- change has no field), so the uniqueness has to be over coalesce(field, '') — hence an
-- expression index rather than a table constraint. The loader also guards with NOT EXISTS, so
-- this index is integrity, not the mechanism.
CREATE UNIQUE INDEX IF NOT EXISTS change_event_dedupe_idx
    ON sonar.change_event (subject_type, subject_id, kind, coalesce(field, ''), detected_at);

-- A table created by some other role in an earlier run would silently break the next
-- `CREATE INDEX IF NOT EXISTS` (DDL needs ownership even when the index already exists), so
-- make ownership explicit and idempotent rather than assuming the SET ROLE above did it.
DO $$
DECLARE
    t text;
BEGIN
    IF pg_has_role(current_user, 'geo_user', 'MEMBER') OR current_user = 'geo_user' THEN
        FOREACH t IN ARRAY ARRAY['source', 'source_version', 'change_event']
        LOOP
            EXECUTE format('ALTER TABLE sonar.%I OWNER TO geo_user', t);
        END LOOP;
    END IF;
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Examples. The queries this schema exists for.
-- ---------------------------------------------------------------------------------------------
--
-- 1. What we watch, by status and kind.
--
--    SELECT status, kind, count(*) FROM sonar.source GROUP BY 1, 2 ORDER BY 3 DESC;
--
-- 2. Sources overdue for a check (what the daily job should pick up).
--
--    SELECT id, url, last_checked_at
--      FROM sonar.source
--     WHERE status <> 'blocked'
--       AND (last_checked_at IS NULL OR last_checked_at < now() - check_every)
--     ORDER BY last_checked_at NULLS FIRST;
--
-- 3. The change feed, newest first, with the source it came from.
--
--    SELECT e.detected_at, e.kind, e.severity, e.subject_id, e.field, e.summary
--      FROM sonar.change_event e
--     ORDER BY e.detected_at DESC
--     LIMIT 50;
--
-- 4. Documents that moved, per issuer, in the last 30 days.
--
--    SELECT s.issuer_slug, count(DISTINCT v.source_id) AS documents, count(*) AS versions
--      FROM sonar.source_version v
--      JOIN sonar.source s ON s.id = v.source_id
--     WHERE v.fetched_at >= now() - interval '30 days'
--     GROUP BY 1
--     ORDER BY versions DESC;
--
-- 5. Dead links we cite (findings, not failures).
--
--    SELECT issuer_slug, url, http_status, error
--      FROM sonar.source
--     WHERE status = 'gone'
--     ORDER BY issuer_slug, url;
