-- The lending-market watcher's tables in schema `sonar` (stocks/watch-lending.mjs, hourly):
-- liquidations whose seized collateral is a tracked stock token, collateral price freeze episodes,
-- and one checkpoint row per watched account. Kamino (KLend), Jupiter Lend, Nest and Loopscale.
--
-- Why not sonar.change_event: a liquidation is market activity, not a change to what a token is,
-- and a wave can be hundreds of rows an hour that the watch page, the change judge, the review
-- queue, the weekly digest and personal watch digests would all pick up. A freeze is an episode
-- that grows and then ends, which an append-only event row cannot say. The latest-events feed
-- reads both tables directly (stocks/lib/events.mjs `lendingEvents`).
--
-- Every time column is the chain's own: a block time, a Pyth publish time, or `block time − age`
-- that KLend logs for a stale price. `listed_at` (when we last listed an account) is operational.
--
-- Idempotent: re-running this file is a no-op.

SET client_min_messages = warning;

DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

-- ---------------------------------------------------------------------------------------------
-- One row per liquidation instruction. `ix_index` is the instruction's position in the
-- transaction's execution order (top-level and inner), so two liquidations in one transaction are
-- two rows. Amounts are in token units (decimals applied). `collateral_amount` is what left the
-- borrower (for Kamino: what the liquidator received plus the protocol's fee);
-- `collateral_to_liquidator` what the liquidator received. `price_source`:
--   protocol-log          the price the lending program logged in the same transaction (KLend)
--   trade-tape-median-1h  the median of our own trade tape (sonar.stock_trade) within ±1 h
--   NULL                  no price: collateral_usd stays NULL, never 0
-- `borrower` is the position's owner where the protocol has one (Kamino obligation owner,
-- Loopscale borrower); Jupiter Lend liquidates by price tick, so it has none.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.lending_liquidation (
    signature                text NOT NULL,
    ix_index                 int NOT NULL,
    slot                     bigint NOT NULL,
    block_time               timestamptz NOT NULL,
    protocol                 text NOT NULL,
    market_id                text NOT NULL,
    market_address           text,
    program_id               text NOT NULL,
    instruction              text NOT NULL,
    mint                     text NOT NULL,
    symbol                   text,
    collateral_amount        numeric,
    collateral_to_liquidator numeric,
    collateral_price_usd     numeric,
    collateral_usd           numeric,
    price_source             text,
    debt_mint                text,
    debt_symbol              text,
    debt_amount              numeric,
    debt_usd                 numeric,
    debt_price_source        text,
    liquidator               text,
    borrower                 text,
    position                 text,
    evidence                 jsonb,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT lending_liquidation_pkey PRIMARY KEY (signature, ix_index)
);

CREATE INDEX IF NOT EXISTS lending_liquidation_time_idx ON sonar.lending_liquidation (block_time DESC);
CREATE INDEX IF NOT EXISTS lending_liquidation_mint_idx ON sonar.lending_liquidation (mint, block_time DESC);

-- ---------------------------------------------------------------------------------------------
-- One row per freeze episode per market per token: a stretch during which the market did not
-- have a price fresh enough to lend, withdraw against debt or liquidate. `observation` says how it
-- was seen:
--   kamino-refresh-log    KLend logged "Price is too old age=A" when refreshing the reserve
--   scope-resume          Scope's ResumeSuspendedPrice (no transaction saw the frozen price)
--   jl-cache-refresh-gap  no successful transaction on a Jupiter Lend Chainlink cache for > 600 s
--   pyth-account-age      a Pyth push account older than the market's max age while the market is open
-- `started_at` is the last update before the freeze; `ended_at` the first fresh observation or
-- update after it (NULL while ongoing), so the real end is at or before it. `last_seen_stale_at`
-- is the latest instant the price was seen stale.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.lending_price_freeze (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol           text NOT NULL,
    market_id          text NOT NULL,
    mint               text NOT NULL,
    symbol             text,
    started_at         timestamptz NOT NULL,
    ended_at           timestamptz,
    last_seen_stale_at timestamptz,
    stale_observations int,
    observation        text NOT NULL,
    cause              text,
    cause_detail       jsonb,
    start_signature    text,
    end_signature      text,
    evidence           jsonb,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT lending_price_freeze_episode_key UNIQUE (market_id, mint, started_at)
);

CREATE INDEX IF NOT EXISTS lending_price_freeze_started_idx ON sonar.lending_price_freeze (started_at DESC);
CREATE INDEX IF NOT EXISTS lending_price_freeze_open_idx ON sonar.lending_price_freeze (mint) WHERE ended_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- One row per watched account: the newest signature processed (the checkpoint every run lists
-- back to), where the first run started (`backfill_from`) and the account's stream state (an open
-- Kamino freeze, a Jupiter Lend cache's last refresh, a Pyth account's open freeze).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.lending_scan (
    account         text PRIMARY KEY,
    protocol        text NOT NULL,
    role            text NOT NULL,
    market_id       text,
    mint            text,
    backfill_from   timestamptz NOT NULL,
    last_signature  text,
    last_slot       bigint,
    last_block_time timestamptz,
    state           jsonb,
    signatures_seen bigint NOT NULL DEFAULT 0,
    listed_at       timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

DO $$
DECLARE
    t text;
BEGIN
    IF pg_has_role(current_user, 'geo_user', 'MEMBER') OR current_user = 'geo_user' THEN
        FOREACH t IN ARRAY ARRAY['lending_liquidation', 'lending_price_freeze', 'lending_scan']
        LOOP
            EXECUTE format('ALTER TABLE sonar.%I OWNER TO geo_user', t);
        END LOOP;
    END IF;
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Examples.
-- ---------------------------------------------------------------------------------------------
--
-- 1. Liquidations of stock collateral, largest first.
--
--    SELECT block_time, protocol, symbol, collateral_amount, collateral_usd, debt_amount, debt_symbol, signature
--      FROM sonar.lending_liquidation
--     ORDER BY collateral_usd DESC NULLS LAST
--     LIMIT 20;
--
-- 2. Freeze episodes with their length, ongoing ones first.
--
--    SELECT market_id, symbol, started_at, ended_at, coalesce(ended_at, last_seen_stale_at) - started_at AS length, cause
--      FROM sonar.lending_price_freeze
--     ORDER BY ended_at IS NOT NULL, started_at DESC;
--
-- 3. How far behind each watched account is (the outcome check reads max(updated_at)).
--
--    SELECT role, count(*), min(last_block_time), max(updated_at) FROM sonar.lending_scan GROUP BY 1;
