-- Legal-entity status watch in schema `sonar` (stocks/watch-entities.mjs): the register state of
-- every legal entity in a tokenized stock's trust chain — issuing SPVs, custodians, transfer
-- agents, parents, security agents — as GLEIF (LEI), Zefix (Swiss commercial register), Companies
-- House and The Gazette (UK insolvency notices) report it. One row per observed CHANGE of state,
-- never one per read: a run that finds the same state only moves `last_confirmed_at` on the latest
-- row. A change that matters (LEI lapsed, entity INACTIVE, company dissolved, insolvency notice,
-- name change, successor) is also a sonar.change_event of kind `entity-status` or `insolvency`.
-- Idempotent: re-running this file is a no-op.

SET client_min_messages = warning;

-- Every object must end up owned by `geo_user` (see db/2026-09-18-sonar-evidence.sql).
DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

-- ---------------------------------------------------------------------------------------------
-- Observations. `entity_key` is the normalised legal name (lib/entities.mjs legalNameKey), the
-- key of stocks/data/entity-registry-ids.json. `identifier` is the source's id: an LEI (gleif), a
-- CHE UID (zefix), a company number (companies-house, gazette).
--
-- `state` is the compared fields as lib/entities.mjs builds them; `state_hash` its stable hash.
-- `source_updated_at` is the SOURCE's own last-update date (GLEIF registration.lastUpdateDate,
-- Zefix shabDate, the newest matched Gazette notice) and is NULL when the source states none
-- (Companies House) — never the fetch time. `observed_at` is when this watcher first saw the
-- state and `last_confirmed_at` the last run that saw it unchanged; both are our clock and claim
-- nothing else.
--
-- `change_kind` is `baseline` for the first observation of an (entity, source, identifier) and
-- `changed` after; `findings` are the differences that became change events, with severity.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sonar.entity_observation (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_key        text NOT NULL,
    entity_name       text NOT NULL,
    source            text NOT NULL,
    identifier        text NOT NULL,
    issuers           text[] NOT NULL DEFAULT '{}',
    state             jsonb NOT NULL,
    state_hash        text NOT NULL,
    source_updated_at timestamptz,
    change_kind       text NOT NULL,
    changed_fields    text[] NOT NULL DEFAULT '{}',
    findings          jsonb NOT NULL DEFAULT '[]'::jsonb,
    url               text,
    observed_at       timestamptz NOT NULL,
    last_confirmed_at timestamptz NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT entity_observation_source_check
        CHECK (source IN ('gleif', 'zefix', 'companies-house', 'gazette')),
    CONSTRAINT entity_observation_change_check CHECK (change_kind IN ('baseline', 'changed')),
    CONSTRAINT entity_observation_once UNIQUE (entity_key, source, identifier, observed_at)
);

CREATE INDEX IF NOT EXISTS entity_observation_latest_idx
    ON sonar.entity_observation (entity_key, source, identifier, observed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS entity_observation_issuers_idx ON sonar.entity_observation USING gin (issuers);

-- The current state per entity and source.
CREATE OR REPLACE VIEW sonar.entity_status_current AS
SELECT DISTINCT ON (entity_key, source, identifier)
       entity_key, entity_name, source, identifier, issuers, state, source_updated_at,
       observed_at, last_confirmed_at, url
  FROM sonar.entity_observation
 ORDER BY entity_key, source, identifier, observed_at DESC, id DESC;

DO $$
BEGIN
    IF pg_has_role(current_user, 'geo_user', 'MEMBER') OR current_user = 'geo_user' THEN
        EXECUTE 'ALTER TABLE sonar.entity_observation OWNER TO geo_user';
        EXECUTE 'ALTER VIEW sonar.entity_status_current OWNER TO geo_user';
    END IF;
END
$$;

-- 2026-10-01: the entity watcher raises `entity-status` (a register state change: LEI lapsed,
-- entity INACTIVE, name change, successor, parent change, Swiss firm status or seat) and
-- `insolvency` (a Gazette insolvency notice, a Swiss bankruptcy/liquidation publication, a UK
-- company in liquidation or administration) events.
-- The allowed change_event kinds are stated in ONE place: db/2026-10-01-sonar-change-event-kinds.sql,
-- applied last (stocks/lib/schema.mjs). A kind list restated here would drop other watchers' kinds.


-- ---------------------------------------------------------------------------------------------
-- Examples.
-- ---------------------------------------------------------------------------------------------
--
-- 1. Every watched entity's current register state, for one issuer.
--
--    SELECT entity_name, source, identifier, state->>'entityStatus' AS lei_entity,
--           state->>'registrationStatus' AS lei_registration, state->>'status' AS register_status,
--           source_updated_at, last_confirmed_at
--      FROM sonar.entity_status_current
--     WHERE 'xstocks-backed' = ANY(issuers) ORDER BY entity_name, source;
--
-- 2. Every recorded change (not baselines), newest first.
--
--    SELECT observed_at, entity_name, source, changed_fields, findings
--      FROM sonar.entity_observation WHERE change_kind = 'changed' ORDER BY observed_at DESC;
--
-- 3. The feed.
--
--    SELECT detected_at, subject_id, severity, summary FROM sonar.change_event
--     WHERE kind IN ('entity-status', 'insolvency') ORDER BY detected_at DESC LIMIT 50;
