-- Append-only editorial decisions for the evidence review workbench. The public queue is rebuilt
-- from source state; this table records who reviewed an item and why, even after it disappears.
SET client_min_messages = warning;

DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

CREATE TABLE IF NOT EXISTS sonar.review_resolution (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_item_id  text NOT NULL,
    event_id        bigint REFERENCES sonar.change_event(id) ON DELETE SET NULL,
    issuer_slug     text,
    field           text,
    issue           text NOT NULL,
    resolution      text NOT NULL,
    note            text NOT NULL,
    reviewer        text NOT NULL,
    previous_text   text,
    current_text    text,
    claim_impact    text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT review_resolution_value_check CHECK (resolution IN (
        'confirmed', 'corrected', 'superseded', 'false-alarm', 'deferred')),
    CONSTRAINT review_resolution_note_check CHECK (length(note) BETWEEN 3 AND 4000),
    CONSTRAINT review_resolution_reviewer_check CHECK (length(reviewer) BETWEEN 2 AND 120)
);

CREATE INDEX IF NOT EXISTS review_resolution_item_idx
    ON sonar.review_resolution (review_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS review_resolution_event_idx
    ON sonar.review_resolution (event_id, created_at DESC);

DO $$
BEGIN
    IF pg_has_role(current_user, 'geo_user', 'MEMBER') OR current_user = 'geo_user' THEN
        ALTER TABLE sonar.review_resolution OWNER TO geo_user;
    END IF;
END
$$;
