-- The reserves watcher's table in schema `sonar` (stocks/watch-reserves.mjs, daily): per token,
-- the issuer's published reserve figure against the supply outstanding on Solana
-- ("proof of reserve"), with the coverage ratios and a status. See stocks/lib/reserves.mjs for
-- the sources and rules.
--
-- One row per READING, not per run: a run whose figures, supply and status equal the latest row
-- for (mint, source) only moves that row's `last_seen_at` and `latest_source_time`. So the table is
-- a history of changes, like sonar.mint_state.
--
-- Time columns: `source_time` / `latest_source_time` are the SOURCE's own publish times (the
-- xStocks feed's per-symbol timestamp) and stay NULL when the source publishes none (Superstate) —
-- never our fetch time. `supply_slot` / `supply_block_time` are the chain's own (getMultipleAccounts
-- context slot and its getBlockTime). `first_seen_at` / `last_seen_at` are when this watcher saw the
-- reading, which is all they claim to be.
--
-- `status`: covered | shortfall | stale | unreadable | not-published | nothing-outstanding.
-- `shortfall_basis`: `issuer` = reserve below the issuer's OWN all-chain circulating figure;
-- `chain` = reserve below what Solana alone proves outstanding (mint supply minus the wallets we
-- attribute to the issuer — so it depends on that attribution); `both`.
-- A missing figure is NULL and never 0; a ratio with a zero or missing denominator is NULL.
--
-- Idempotent: re-running this file is a no-op.

SET client_min_messages = warning;

DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

CREATE TABLE IF NOT EXISTS sonar.reserve_observation (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mint                text NOT NULL,
    symbol              text,
    issuer              text NOT NULL,
    source              text NOT NULL,
    source_kind         text,
    source_url          text,
    status              text NOT NULL CHECK (status IN ('covered', 'shortfall', 'stale', 'unreadable', 'not-published', 'nothing-outstanding')),
    shortfall_basis     text CHECK (shortfall_basis IN ('issuer', 'chain', 'both')),
    stale               boolean,
    reserve             numeric,
    issuer_circulating  numeric,
    source_time         timestamptz,
    latest_source_time  timestamptz,
    supply_raw          numeric,
    excluded_raw        numeric,
    decimals            int,
    ui_multiplier       numeric,
    chain_outstanding   numeric,
    supply_slot         bigint,
    supply_block_time   timestamptz,
    coverage_issuer     numeric,
    coverage_chain      numeric,
    reasons             jsonb NOT NULL DEFAULT '[]'::jsonb,
    detail              jsonb NOT NULL DEFAULT '{}'::jsonb,
    reading_hash        text NOT NULL,
    first_seen_at       timestamptz NOT NULL,
    last_seen_at        timestamptz NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS reserve_observation_latest_idx ON sonar.reserve_observation (mint, source, id DESC);
CREATE INDEX IF NOT EXISTS reserve_observation_status_idx ON sonar.reserve_observation (status, last_seen_at DESC)
    WHERE status IN ('shortfall', 'stale', 'unreadable');
