-- `sonar.change_judgment` (stocks/EVIDENCE.md §2.3 "LLM judge", next-steps.md iteration item 4):
-- one row per model assessment of one detected document change — "does this change alter what a
-- holder owns, can do, or can have done to them?" — with the tokens and dollars that call cost.
-- Written by stocks/judge-changes.mjs from a Message Batches run. A judgment is shown beside the
-- diff as a MODEL ASSESSMENT and is never the only signal; `quoted_change` only ever holds
-- fragments found verbatim in the change text the model was shown (anything else is kept in
-- `rejected_quotes` and the row is `invalid`).
--
-- Apply AFTER db/2026-09-18-sonar-evidence.sql: the foreign key needs sonar.change_event.
-- Idempotent: re-running this file is a no-op.

SET client_min_messages = warning;

DO $$
BEGIN
    IF current_user <> 'geo_user' AND pg_has_role(current_user, 'geo_user', 'MEMBER') THEN
        EXECUTE 'SET ROLE geo_user';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sonar;

-- `change_event_id` is the representative event; `covers_event_ids` every event of the same change
-- (a legal-term event and the quote-lost events raised by the same fetch are one change, judged
-- once), and `dedupe_key` (source URL | content hash) is that change's identity, which is what a
-- rerun uses to skip it. `cost_usd` is the batch price of THIS call from the shared rate table
-- (agents/lib/llm-cost), never null: an errored batch item is billed nothing and stores 0.
CREATE TABLE IF NOT EXISTS sonar.change_judgment (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_event_id       bigint NOT NULL REFERENCES sonar.change_event(id) ON DELETE CASCADE,
    covers_event_ids      jsonb NOT NULL DEFAULT '[]'::jsonb,
    dedupe_key            text NOT NULL,
    model                 text NOT NULL,
    prompt_version        text NOT NULL,
    material              boolean,
    severity              text,
    affects               jsonb NOT NULL DEFAULT '[]'::jsonb,
    summary               text,
    quoted_change         jsonb NOT NULL DEFAULT '[]'::jsonb,
    rejected_quotes       jsonb NOT NULL DEFAULT '[]'::jsonb,
    invalid_reasons       jsonb NOT NULL DEFAULT '[]'::jsonb,
    confidence            numeric,
    status                text NOT NULL,
    input_tokens          int NOT NULL DEFAULT 0,
    output_tokens         int NOT NULL DEFAULT 0,
    cache_read_tokens     int NOT NULL DEFAULT 0,
    cache_creation_tokens int NOT NULL DEFAULT 0,
    cost_usd              numeric NOT NULL,
    batch_id              text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT change_judgment_event_model_prompt_key UNIQUE (change_event_id, model, prompt_version),
    CONSTRAINT change_judgment_status_check CHECK (status IN ('valid', 'invalid', 'error')),
    CONSTRAINT change_judgment_severity_check
        CHECK (severity IS NULL OR severity IN ('info', 'caution', 'warning', 'critical')),
    CONSTRAINT change_judgment_confidence_check
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT change_judgment_cost_check CHECK (cost_usd >= 0),
    -- A valid judgment has every field the schema requires.
    CONSTRAINT change_judgment_valid_complete_check CHECK (status <> 'valid' OR (
        material IS NOT NULL AND severity IS NOT NULL AND summary IS NOT NULL AND confidence IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS change_judgment_dedupe_idx ON sonar.change_judgment (dedupe_key, model, prompt_version);
CREATE INDEX IF NOT EXISTS change_judgment_status_idx ON sonar.change_judgment (status);

DO $$
BEGIN
    IF pg_has_role(current_user, 'geo_user', 'MEMBER') OR current_user = 'geo_user' THEN
        EXECUTE 'ALTER TABLE sonar.change_judgment OWNER TO geo_user';
    END IF;
END
$$;

-- Examples.
--
-- 1. The model assessment beside each change, newest first.
--
--    SELECT e.detected_at, e.kind, e.summary AS change, j.severity, j.material, j.summary AS assessment,
--           j.quoted_change, j.confidence, j.model
--      FROM sonar.change_judgment j
--      JOIN sonar.change_event e ON e.id = j.change_event_id
--     WHERE j.status = 'valid'
--     ORDER BY e.detected_at DESC;
--
-- 2. What judging has cost, per model and prompt version.
--
--    SELECT model, prompt_version, status, count(*), sum(input_tokens) AS input, sum(output_tokens) AS output,
--           sum(cost_usd) AS usd
--      FROM sonar.change_judgment GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;
