// Shared report presentation: pure scoped inputs, topic navigation and escaped markup.
(function(root,factory){
    if(typeof module==='object'&&module.exports)module.exports=factory(require('./research.js'),require('./visual-profile.js'),require('./failure-scenario.js'),require('./monitor.js'),require('./token-story.js'));
    else root.__rwaReportView=factory(root.__rwaResearch,root.__rwaVisualProfile,root.__rwaFailureScenario,root.__rwaMonitor,root.__rwaTokenStory);
})(this,function(research,visual,scenarios,monitor,story){
    'use strict';
    const esc=visual.escape;
    const TOPICS=[{id:'overview',label:'Overview',icon:'document'},...visual.FEATURES,{id:'sources',label:'Sources',icon:'document'}];
    const LEGAL_FORMS={'spv-claim-redeemable':'Redeemable claim through an issuing vehicle','registered-share':'Registered company share','structured-note':'Structured investment note','spv-synthetic':'Synthetic exposure through an issuing vehicle','debt-note':'Debt note','derivative':'Derivative contract','tracker-certificate':'Tracker certificate'};
    const legalForm=v=>LEGAL_FORMS[v]||v;
    const EXIT_LABELS={obligor:'Who owes the payout',processor:'Who operates the route',onboarding:'Who can use it',entitlementOnTransfer:'Rights after transfer',settlement:'What you receive and when',minimumAndFees:'Minimums and costs',independentRoute:'Route without the issuer',availability:'Evidence of operation'};
    const STATES={strength:'Strength',condition:'Condition',problem:'Problem',unknown:'Not established','not-applicable':'Not applicable'};
    const date=v=>v?esc(String(v).replace(/T.*$/,'')):'Date not recorded';
    function short(text,max=230){const s=String(text||'');return s.length<=max?s:s.slice(0,max).replace(/\s+\S*$/,'')+'…';}
    function title(text){return String(text||'').replace(/^Programme evidence:\s*/,'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[._-]/g,' ').replace(/^./,c=>c.toUpperCase());}
    function topicForHash(hash){const key=String(hash||'').replace(/^#/,'');if(key==='story'||TOPICS.some(t=>t.id===key))return key;if(key==='failureScenario')return 'failure';return visual.FEATURES.find(f=>f.dimensions.includes(key.replace(/^finding-/,'')))?.id||'overview';}
    function view(product,contextId,options={}){
        const context=product.contexts.find(c=>c.id===contextId);if(!context)throw new Error('Unknown report holder context');
        const deployment=options.deploymentId?product.deployments.find(d=>d.id===options.deploymentId):null;
        if(options.deploymentId&&!deployment)throw new Error('Unknown report deployment');
        const bound=!deployment||Boolean(product.instrument&&deployment.instrumentId===product.instrument.id);
        const profile=visual.profile(product,contextId,options);
        const subject=product.instrument||product.programme;
        const features=profile.features.map(f=>({...f,findings:f.findings.map(finding=>({...finding,question:research.DIMENSIONS[finding.dimension],sources:finding.sourceIds.map(id=>product.sources.find(s=>s.id===id)).filter(Boolean)}))}));
        const canStory=story.available({product,context,bound});
        return {product,context,deployment,bound,subject,features,topic:topicForHash(options.hash)==='story'&&!canStory?'overview':topicForHash(options.hash),scenarioMode:options.scenarioMode||'normal',scope:product.kind==='programme'?'Programme research':'Product research',checkedAt:product.reviewedAt||product.evidenceCheckedAt,
            facts:bound?product.reportDetails?.facts||[]:[],cases:bound?product.reportDetails?.cases||[]:[],exit:bound?product.exitDetails[contextId]||{}:{},assetModule:bound?product.assetModule:null};
    }
    function sourceButton(dimension,count){return `<button type="button" class="report-evidence-button" data-report-evidence="${esc(dimension)}">${count?`Evidence · ${count} source${count===1?'':'s'}`:'Evidence gap'} <span aria-hidden="true">↗</span></button>`;}
    function findingHtml(f){const explanation=f.note||f.summary;return `<article class="report-finding" id="finding-${esc(f.dimension)}"><p class="report-question">${esc(f.question)}</p><h3 data-tone="${esc(f.tone)}"><span aria-hidden="true">${esc(visual.TONES[f.tone].mark)}</span> ${esc(f.label)}</h3><p>${esc(short(explanation))}</p><div class="report-finding-meta"><span class="report-tone" data-tone="${esc(f.tone)}">${esc(STATES[f.tone])}</span>${sourceButton(f.dimension,f.sources.length)}</div>${explanation!==f.summary||f.summary.length>230?`<details class="report-reading"><summary>Read the full finding</summary><p>${esc(f.summary)}</p><small>${esc(research.BASES[f.basis])} · Reviewed ${date(f.checkedAt)}</small></details>`:''}</article>`;}
    function diagram(v){const p=v.product;const custody=v.bound&&p.scenarioActors?.length?p.scenarioActors.map(a=>a.name).join(' · '):p.exposure.label;const nodes=[{topic:'ownership',icon:'document',label:'Your claim',name:v.bound?short(legalForm(v.subject.legalForm),90):'Individual terms unverified',state:v.features[0].findings[0].state},{topic:'backing',icon:'vault',label:'Assets and custody',name:short(custody,90),state:v.features[1].findings[0].state},{topic:'exit',icon:'door',label:'Route out',name:v.features[3].findings[0].label,state:v.features[3].findings[0].state}];return `<section class="report-arrangement" aria-label="Reviewed relationships"><div class="report-arrangement-root"><small>${v.bound?esc(v.scope):'Selected token · legal binding unverified'}</small><strong>${esc(v.bound?p.scenarioIssuer||v.subject.issuer||p.name:v.deployment.symbol||p.ticker||p.name)}</strong></div><div class="report-arrangement-branches">${nodes.map(n=>`<a href="#${n.topic}" data-state="${esc(n.state)}">${visual.icon(n.icon)}<small>${esc(n.label)}</small><span>${esc(n.name)}</span></a>`).join('')}</div><p class="report-caption">${v.bound?'Select a relationship to inspect its findings.'+(p.scenarioActors?.length?' Custody names may refer to sampled products; their scope is explained under Backing.':''):'The selected address has not been linked to reviewed holder terms. Its chain observations are available under Controls.'}</p></section>`;}
    function overview(v){return `${story.available(v)?`<a class="report-story-entry" href="#story"><span aria-hidden="true">▶</span><span><strong>Watch the story</strong><small>A narrated tour of the claim, the keys and the route out</small></span><span aria-hidden="true">→</span></a>`:''}${diagram(v)}<h2>Your position, in five questions</h2><div class="report-overview-findings">${v.features.map(f=>`<a href="#${f.id}" class="report-overview-row">${visual.icon(f.icon)}<span><strong>${esc(f.label)}</strong><span>${f.findings.map(x=>`<span data-tone="${esc(x.tone)}">${esc(visual.TONES[x.tone].mark)} ${esc(x.label)}</span>`).join('')}</span></span><span aria-hidden="true">→</span></a>`).join('')}</div><p class="report-caption">Research reviewed ${date(v.checkedAt)}. Individual observations carry their own dates.</p>`;}
    function detailList(rows){return `<dl class="report-facts">${rows.map(([label,text])=>`<div><dt>${esc(label)}</dt><dd>${text?esc(text):'Not established for this holder context'}</dd></div>`).join('')}</dl>`;}
    function factDetails(v,topic){const facts=v.facts.filter(f=>f.topic===topic);return facts.length?`<section class="report-supporting"><h3>Programme details</h3>${facts.map(f=>`<details><summary>${esc(f.label)}${f.summary.length<55?' · '+esc(f.summary):''}</summary><p>${esc(f.summary)}</p>${sourceButton('fact:'+f.id,f.sourceIds.length)}</details>`).join('')}</section>`:'';}
    function assetModule(v){return v.assetModule?`<section class="report-supporting"><h3>${esc(v.assetModule.label)}</h3><p>${esc(v.assetModule.summary)}</p>${sourceButton('asset',v.assetModule.sourceIds.length)}</section>`:'';}
    function backing(v){const p=v.product;return `${p.exposure.id!=='gold'?assetModule(v):''}${v.features.find(f=>f.id==='backing').findings.map(findingHtml).join('')}${v.bound&&p.scenarioActors?.length?`<section class="report-supporting"><h3>Named custody and brokerage parties</h3>${p.scenarioActors.map((a,i)=>`<details><summary>${esc(a.name)} <small>${esc(a.role)}</small></summary><p>${esc(a.note)}</p>${sourceButton('actor:'+i,a.sourceIds.length)}</details>`).join('')}</section>`:''}${v.bound&&p.relationships?.length?`<section class="report-supporting"><h3>Portfolio and wrapper dependencies</h3>${p.relationships.map(r=>`<p><strong>${esc(r.target)}</strong><br>${esc(r.backingCountPolicy)}</p>`).join('')}</section>`:''}${v.bound?`<section class="report-supporting"><h3>What the evidence measures</h3>${p.evidenceProfiles.map((e,i)=>`<details><summary>${esc(e.method)} <small>${esc(e.availability.replaceAll('-',' '))}</small></summary><p>${esc(e.scope)}</p><p>${esc(e.limit)}</p>${e.sourcePeriod?`<p class="report-caption">Measurement period: ${esc(e.sourcePeriod)}</p>`:''}${sourceButton('profile:'+i,e.sourceIds.length)}</details>`).join('')}</section>`:''}`;}
    function valueText(value){if(value===null||value===undefined)return 'Not recorded';if(Array.isArray(value))return value.map(valueText).join(' · ');if(typeof value==='object')return Object.entries(value).map(([k,v])=>title(k)+': '+valueText(v)).join('; ');return String(value);}
    function controls(v){const d=v.deployment;return `${v.features.find(f=>f.id==='controls').findings.map(findingHtml).join('')}${factDetails(v,'controls')}<section class="report-supporting"><h3>Token and network observations</h3><div data-report-deployment-slot></div>${!d?`<p>Select one of ${v.product.deployments.length} indexed addresses to inspect its recorded powers and monitoring.</p>`:`<p class="report-token-title">${esc(d.symbol||v.product.ticker||v.product.name)} · ${esc(d.network)}</p><code>${esc(d.address)}</code><p>${esc(d.identity)}</p>${detailList([['Monitor',monitor.coverage(d,d.monitoring).replaceAll('-',' ')],['Latest successful read',d.monitoring?.lastSuccessAt||d.chainCheckedAt||null],['Latest attempt',d.monitoring?.lastAttemptStatus||null]])}${d.monitoring?.lastError?`<p class="report-error">${esc(d.monitoring.lastError)}</p>`:''}<p>${esc(d.controls.summary)}</p>${d.observation?`<details><summary>Observed powers and chain fields</summary>${detailList(Object.entries(d.observation.fields).map(([k,x])=>[title(k),x.state==='unknown'?'Not decoded: '+x.reason:x.value===null?'None in this observed field':valueText(x.value)]))}<p class="report-caption">Block / slot: ${esc(d.observation.blockNumber||d.observation.slot)} · ${date(d.observation.blockTimestamp)}</p><p>${esc(d.observation.limitations)}</p></details>`:''}${d.legacy?`<details><summary>Retained token observations</summary><p class="report-caption">These observations retain their original dates.</p>${detailList(Object.entries(d.legacy.sourceDates||{}).map(([k,x])=>[title(k),x]))}${detailList(Object.entries(d.legacy.control||{}).map(([k,x])=>[title(k),valueText(x)]))}</details>`:''}${d.report?`<a href="./${esc(d.report)}">Trading, liquidity and token history →</a>`:''}${sourceButton('deployment',d.sourceIds.length)}`}</section>`;}
    function exit(v){const values=['onboarding','settlement','minimumAndFees'];return `${v.features.find(f=>f.id==='exit').findings.map(findingHtml).join('')}${v.bound?`<section class="report-supporting"><h3>Using the route</h3><ol class="report-exit-steps">${values.map((key,i)=>`<li><span class="report-step-number">${i+1}</span><div><strong>${esc(EXIT_LABELS[key])}</strong><p>${esc(short(v.exit[key]||'Not established for this holder context',260))}</p>${v.exit[key]?.length>260?`<details><summary>Full terms and restrictions</summary><p>${esc(v.exit[key])}</p></details>`:''}</div></li>`).join('')}</ol><details><summary>Obligor, operators and operational evidence</summary>${detailList(Object.entries(v.exit).filter(([k])=>!values.includes(k)).map(([k,value])=>[EXIT_LABELS[k]||title(k),value]))}</details></section>`:''}${factDetails(v,'exit')}`;}
    function failure(v){const p=v.product;const s=scenarios.scenario(p,v.context.id,v.scenarioMode,v.deployment?{deploymentId:v.deployment.id}:{});const routes={described:'Described in the research',conditional:'Depends on conditions',unknown:'Recovery route not established','not-applicable':'Not applicable'};return `${v.features.find(f=>f.id==='failure').findings.map(findingHtml).join('')}<section class="report-supporting" id="failureScenario"><h3>Explore a failure scenario</h3><div class="scenario-controls" role="group" aria-label="Hypothetical scenario">${Object.entries(scenarios.MODES).map(([id,label])=>`<button type="button" class="button" data-scenario="${id}" aria-pressed="${id===v.scenarioMode}">${esc(label)}</button>`).join('')}</div><div class="report-scenario-routes">${[['claim','Your claim','document'],['custody','Assets and custody','vault'],['exit','Route out','door']].map(([key,label,icon])=>`<div data-route="${esc(s.routes[key])}" data-affected="${s.affected==='issuer'&&key==='claim'||s.affected==='custodian'&&key==='custody'}">${visual.icon(icon)}<strong>${label}</strong><small>${esc(routes[s.routes[key]])}</small></div>`).join('')}</div><p class="report-caption">Hypothetical scenario · ${esc(s.label)}. A party being unavailable is different from insolvency.</p>${v.scenarioMode!=='normal'?`<p>${esc(s.summary)}</p>${sourceButton('scenario',s.sourceIds.length)}`:''}</section>${v.cases.length?`<section class="report-supporting"><h3>Other researched scenarios</h3><label class="report-search-label">Find a scenario<input type="search" data-report-case-search placeholder="Try stolen keys, frozen token or insolvency"></label><div data-report-cases>${casesMarkup(v,'')}</div></section>`:''}`;}
    function casesMarkup(v,query){return v.cases.filter(c=>`${c.label} ${c.outcome}`.toLowerCase().includes(query.toLowerCase())).map(c=>`<details><summary>${esc(c.label)} <small>${esc(c.status)}</small></summary><p>${esc(c.outcome)}</p>${sourceButton('case:'+c.id,c.sourceIds.length)}<p class="report-caption">Programme research · ${date(c.checkedAt)}</p></details>`).join('')||'<p>No researched scenarios match.</p>';}
    function sourceGroups(p, query='') {
        const groups=new Map(), needle=query.toLowerCase();
        for(const source of p.sources){
            if(!`${source.title} ${source.url} ${source.locator}`.toLowerCase().includes(needle))continue;
            const key=source.url;
            if(!groups.has(key))groups.set(key,{url:source.url,sources:[]});
            groups.get(key).sources.push(source);
        }
        return [...groups.values()];
    }
    function sourceRows(p,query=''){
        return sourceGroups(p,query).map(g=>`<details class="report-source"><summary>${esc(title(g.sources[0].title))}<small>${esc(short(g.url.replace(/^https?:\/\//,''),110))} · ${g.sources.length} retained citation${g.sources.length===1?'':'s'}</small></summary><a href="${esc(g.url)}" target="_blank" rel="noopener">Open original source ↗</a>${g.sources.map(s=>`<details><summary>${esc(title(s.title))} · ${esc(s.locator)}</summary>${s.quote?`<blockquote>${esc(s.quote)}</blockquote>`:''}<p class="report-caption">${s.documentDate?'Published '+date(s.documentDate)+' · ':''}${s.effectiveDate?'Effective '+date(s.effectiveDate)+' · ':''}Checked ${date(s.checkedAt)}</p></details>`).join('')}</details>`).join('')||'<p>No sources match.</p>';
    }
    function sourcesTopic(v){const p=v.product;return `<h2>Sources and review scope</h2><details><summary>Identity, holder context and reviewed terms</summary>${detailList([['Holder context',v.context.label],['Legal interest',legalForm(v.subject.legalForm)],['Issuer',v.subject.issuer],['Identity coverage',v.subject.identity],['Review scope',v.subject.scope],['Terms identifier',v.context.termsId]])}</details><label class="report-search-label">Search ${sourceGroups(p).length} documents and ${p.sources.length} citations<input type="search" data-report-source-search placeholder="Find a document, clause or source"></label><div data-report-source-list>${sourceRows(p)}</div><p><a href="./rwa-research.json">Download research data</a>${p.legacyReport?` · <a href="./${esc(p.legacyReport)}">Original stock dossier</a>`:''}</p>`;}
    function render(v){const topics=story.available(v)?[TOPICS[0],{id:'story',label:'Story',icon:'document'},...TOPICS.slice(1)]:TOPICS;const topic=topics.find(t=>t.id===v.topic);let content;if(v.topic==='story')content='<div data-token-story></div>';else if(v.topic==='overview')content=overview(v);else if(v.topic==='ownership')content=v.features[0].findings.map(findingHtml).join('')+(v.product.exposure.id==='gold'?assetModule(v):'')+factDetails(v,'ownership');else if(v.topic==='backing')content=backing(v);else if(v.topic==='controls')content=controls(v);else if(v.topic==='exit')content=exit(v);else if(v.topic==='failure')content=failure(v);else content=sourcesTopic(v);return `<nav class="report-topic-nav" aria-label="Report topics"><div class="report-topic-links">${topics.map(t=>`<a href="#${t.id}"${t.id===v.topic?' aria-current="page"':''}>${visual.icon(t.icon)}${esc(t.label)}</a>`).join('')}</div><label class="report-topic-mobile">Explore this report<select data-report-topic-picker>${topics.map(t=>`<option value="${t.id}"${t.id===v.topic?' selected':''}>${esc(t.label)}</option>`).join('')}</select></label><a class="report-compare-link" href="./compare.html?left=${encodeURIComponent(v.product.id)}&leftContext=${encodeURIComponent(v.context.id)}">Compare →</a></nav><div class="report-reading-panel" id="reportPanel"><p class="report-panel-eyebrow">${esc(v.scope)}${v.deployment?' · '+esc(v.deployment.symbol||v.product.ticker||v.deployment.network):''}</p><h2 class="report-topic-title" tabindex="-1">${esc(topic.label)}</h2>${!v.bound?`<p class="report-binding-note">Individual holder terms have not been verified for this address. <button type="button" data-report-programme>View ${v.product.kind==='programme'?'programme':'product'} research</button></p>`:''}${content}</div>`;}
    function evidence(v,key){let finding=null,ids=[],heading='Supporting evidence',description='';if(key.startsWith('fact:')){const f=v.facts.find(f=>f.id===key.slice(5));ids=f?.sourceIds||[];heading=f?.label||heading;}else if(key.startsWith('case:')){const c=v.cases.find(c=>c.id===key.slice(5));ids=c?.sourceIds||[];heading=c?.label||heading;description=c?.outcome||'';}else if(key.startsWith('actor:')){const a=v.bound?v.product.scenarioActors?.[Number(key.slice(6))]:null;ids=a?.sourceIds||[];heading=a?.name||heading;}else if(key.startsWith('profile:')){const p=v.bound?v.product.evidenceProfiles[Number(key.slice(8))]:null;ids=p?.sourceIds||[];heading=p?.method||heading;}else if(key==='asset'){ids=v.assetModule?.sourceIds||[];heading=v.assetModule?.label||heading;}else if(key==='deployment'){ids=v.deployment?.sourceIds||[];heading='Deployment identity sources';}else if(key==='scenario'){const s=scenarios.scenario(v.product,v.context.id,v.scenarioMode,v.deployment?{deploymentId:v.deployment.id}:{});ids=s.sourceIds;heading=s.label;}else{finding=v.features.flatMap(f=>f.findings).find(f=>f.dimension===key);ids=finding?.sourceIds||[];heading=finding?.question||heading;}const sources=ids.map(id=>v.product.sources.find(s=>s.id===id)).filter(Boolean);return {heading,finding,sources,description};}
    function renderEvidence(v,key){const e=evidence(v,key);return `<div class="report-evidence-heading"><div><p class="eyebrow">Evidence</p><h2 id="reportEvidenceTitle">${esc(e.heading)}</h2></div><button type="button" class="report-close" data-report-close aria-label="Close evidence">×</button></div>${e.finding?`<p>${esc(e.finding.summary)}</p><p class="report-caption">${esc(research.BASES[e.finding.basis])} · Reviewed ${date(e.finding.checkedAt)}</p>`:e.description?`<p>${esc(e.description)}</p>`:''}${e.sources.length?e.sources.map(s=>`<article class="report-evidence-source"><h3>${esc(title(s.title))}</h3><a href="${esc(s.url)}" target="_blank" rel="noopener">Open original source ↗</a><p>${esc(s.locator)}</p>${s.quote?`<details><summary>Retained quotation</summary><blockquote>${esc(s.quote)}</blockquote></details>`:''}<p class="report-caption">${s.documentDate?'Published '+date(s.documentDate)+' · ':''}${s.effectiveDate?'Effective '+date(s.effectiveDate)+' · ':''}Checked ${date(s.checkedAt)}</p></article>`).join(''):'<p>No source establishes this answer for the selected holder context and terms.</p>'}`;}
    return {TOPICS,topicForHash,view,render,renderEvidence,evidence,sourceGroups,sourceRows,casesMarkup};
});
